# === APPLICATION ===
quarkus.application.name=user-service
quarkus.application.version=1.0.0

# === HTTP (task-service usa 8080) ===
quarkus.http.port=8081

# === DATASOURCE — dev ===
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=userservice
quarkus.datasource.password=userservice
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/usersdb

# === HIBERNATE ORM ===
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true

# === PRODUCTION OVERRIDES ===
%prod.quarkus.datasource.jdbc.url=${DB_URL}
%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.hibernate-orm.database.generation=update
%prod.quarkus.hibernate-orm.log.sql=false
%prod.quarkus.hibernate-orm.format-sql=false

# === OPENAPI + SWAGGER UI ===
quarkus.smallrye-openapi.info-title=User Service API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=User management microservice — Quarkus, JPA/Panache, PostgreSQL
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
