# === APPLICATION ===
quarkus.application.name=quarkus-task-manager-api
quarkus.application.version=1.0.0

# === HTTP ===
quarkus.http.port=8080

# === DATASOURCE — defaults apply to dev profile ===
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=taskmanager
quarkus.datasource.password=taskmanager
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/taskmanagerdb

# === HIBERNATE ORM — dev defaults ===
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true

# === PRODUCTION OVERRIDES ===
%prod.quarkus.datasource.jdbc.url=${DB_URL}
%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.hibernate-orm.database.generation=update
%prod.quarkus.hibernate-orm.log.sql=false
%prod.quarkus.hibernate-orm.format-sql=false

# === REST CLIENT — user-service ===
quarkus.rest-client.user-service.url=http://localhost:8081
%prod.quarkus.rest-client.user-service.url=${USER_SERVICE_URL}

# === OPENAPI + SWAGGER UI ===
quarkus.smallrye-openapi.info-title=Task Manager API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=A RESTful API for managing tasks — built with Quarkus, JPA/Panache, and PostgreSQL
quarkus.smallrye-openapi.info-contact-name=Axel E. de la Canal
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
